from __future__ import annotations

from typing import Any

from app.agent_runtime.tools.contracts import ToolContract
from app.agent_runtime.tools.registry import ToolContractRegistry

from .output_schemas import output_schema_for_tool
from .schemas import input_schema_for_tool, internal_input_schema_for_tool


def _tool_contract(*, name: str, **values: Any) -> ToolContract:
    return ToolContract(
        name=name,
        input_schema=input_schema_for_tool(name),
        internal_input_schema=internal_input_schema_for_tool(name),
        output_schema=output_schema_for_tool(name),
        **values,
    )


def default_tool_registry() -> ToolContractRegistry:
    registry = ToolContractRegistry()
    registry.register(
        _tool_contract(
            name="profile_read",
            domain="profiles",
            description=(
                "读取当前用户的妈妈资料和宝宝资料，不包含奶量产出和摄入记录或完整病史。"
                "当回答母婴资料问题、进行奶量分析需要基础背景，或更新前需要定位宝宝时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="profile_update",
            domain="profiles",
            description=(
                "更新妈妈的称呼、年龄、孕产和喂养基础资料，以及已有宝宝的出生资料和当前分娩关联；"
                "不更新奶量或生长记录。当用户在对话中提供需要持久化的新资料、更正现有资料或要求清空资料时使用。"
            ),
            effect_scope="user_resource",
            action_types=(
                "profile.update",
                "profile.current_infants.replace",
            ),
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="schedule_timeline_read",
            domain="schedule_timeline",
            description=(
                "读取当前用户指定日期范围内的跨领域计划与日程，并关联喂养、吸奶和宝宝生长实际记录。"
                "当需要查看过去、今天或未来的安排和执行情况，或在修改前定位任务或记录时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="schedule_timeline_mutate",
            domain="schedule_timeline",
            description=(
                "创建、更新、删除或调整跨领域日程，管理喂养、吸奶和宝宝生长实际记录，"
                "并支持奶量计划的冲突感知批量重排。当需要根据用户本轮已表达的意图安排、调整、"
                "取消或完成事项，补录、修改或删除实际记录，或重排奶量任务时使用。"
            ),
            effect_scope="user_resource",
            action_types=(
                "plans.task.create",
                "plans.task.update",
                "plans.task.complete",
                "plans.task.delete",
                "plans.milk_schedule.reschedule",
                "records.feeding_record.create",
                "records.feeding_record.update",
                "records.feeding_record.delete",
                "records.pumping_record.create",
                "records.pumping_record.update",
                "records.pumping_record.delete",
                "records.growth_record.create",
                "records.growth_record.update",
                "records.growth_record.delete",
            ),
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="milk_analysis_manage",
            domain="lactation_analysis",
            description=(
                "读取奶量状态，并管理完整奶量分析的资料采集与评估流程。"
                "当需要判断奶量是否充足或了解近期趋势，或当前系统分析流程需要启动、继续或完成时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="diary_read",
            domain="diary",
            description=(
                "读取当前用户某天的完整日记，或日期范围内的日记摘要。"
                "当需要查看日记、确认待修改或删除的目标，或更新前取得完整旧正文时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="diary_mutate",
            domain="diary",
            description=(
                "创建、完整更新或删除当前用户的日记。"
                "当用户表达记录、完整改写或删除某日日记的意图时使用。"
            ),
            effect_scope="user_resource",
            action_types=("diary.entry.save", "diary.entry.delete"),
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="devices_guidance_manage",
            domain="devices",
            description=(
                "读取 Momcozy 官方设备指导资料，并管理连续开箱指导流程。"
                "当回答受支持设备的安装、清洁、充电、蓝牙、法兰或操作问题需要官方指导，"
                "或当前开箱流程需要启动、恢复、推进或取消时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="pump_models_read",
            domain="devices",
            description=(
                "读取 Momcozy 官方吸奶器型号与产品事实。"
                "当型号比较、价格或功能核对、适用场景判断或选购建议需要官方产品事实时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="conversation_history_image_read",
            domain="images",
            description=(
                "将当前对话历史中由智能体展示过的一张图片重新载入模型上下文。"
                "当本轮请求依赖该历史图片、但模型无法直接查看其内容时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="plan_read",
            domain="plans",
            description=(
                "读取当前用户当前有效的计划列表或指定计划详情，不读取计划内日程。"
                "当需要查看或回答已有计划问题、修改前获取最新版本，或删除前定位目标计划时使用。"
            ),
            effect_scope="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="plan_mutate",
            domain="plans",
            description=(
                "创建奶量或孕期计划，更新已有计划的标题或摘要，或删除整个计划；"
                "不修改计划内单项日程。当奶量分析或孕期资料采集已满足计划生成条件，"
                "或用户要修改计划标题、摘要或删除整份计划时使用。"
            ),
            effect_scope="user_resource",
            action_types=(
                "plans.milk_plan.create",
                "pregnancy.plan.create",
                "plans.plan.update",
                "plans.plan.delete",
            ),
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy_intake_manage",
            domain="pregnancy_intake",
            description=(
                "收集并管理生成孕期计划所需的信息。"
                "当用户的孕期计划目标需要启动资料采集、处理当前回答，"
                "或暂停、恢复、更正或放弃采集流程时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_manage",
            domain="hospital_bag",
            description=(
                "收集待产包所需信息，并在信息完整后生成清单。"
                "当用户的待产包目标需要启动或恢复资料采集、基于完整可信信息生成清单，"
                "或重新开始采集时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_cart_mutate",
            domain="hospital_bag",
            description=(
                "修改当前用户已有的待产包购物车。"
                "当需要根据用户已表达的预算或商品调整意图，优化预算、移除或恢复默认商品、"
                "替换商品、修改数量、标记已有物品、切换吸奶器或重置购物车时使用。"
            ),
            effect_scope="user_resource",
            action_types=("hospital_bag.cart.update",),
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="ibclc_consult_card_create",
            domain="lactation",
            description=(
                "创建 IBCLC 咨询入口卡片。"
                "当用户明确要求联系顾问，或明确同意上一轮的 IBCLC 咨询建议时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="support_ticket_draft_create",
            domain="support",
            description=(
                "创建可编辑的 Momcozy 售后工单草稿，不提交正式工单。"
                "当用户本轮明确同意整理售后工单，且已提供可概括的问题事实时使用。"
            ),
            effect_scope="agent_internal",
            blocking_policy="must_wait",
            result_dependency="final_response",
            timeout_seconds=15,
        )
    )
    return registry
