from __future__ import annotations

from copy import deepcopy
from typing import Any

from app.core.errors import ApiError


JsonSchema = dict[str, Any]


_TOOL_INPUT_SCHEMAS: dict[str, JsonSchema] = {'profile_read': {'type': 'object',
                  'additionalProperties': False,
                  'properties': {'infant_scope': {'type': 'string',
                                                  'enum': ['current_delivery', 'all'],
                                                  'default': 'current_delivery',
                                                  'description': '宝宝读取范围。current_delivery '
                                                                 '仅返回当前这次分娩的宝宝，供奶量分析使用；all '
                                                                 '返回当前用户的全部宝宝，供通用资料核对和选择 infant_id 使用。'}}},
 'profile_update': {'type': 'object',
                   'additionalProperties': False,
                   'minProperties': 2,
                   'properties': {'operation': {'type': 'string', 'enum': ['update']},
                                  'mother': {'type': 'object',
                                             'additionalProperties': False,
                                             'minProperties': 1,
                                             'properties': {'preferred_name': {'anyOf': [{'type': 'string',
                                                                                          'minLength': 1,
                                                                                          'maxLength': 120},
                                                                                         {'type': 'null'}],
                                                                               'description': '妈妈希望使用的称呼；传 '
                                                                                              'null 表示清空。'},
                                                            'age': {'anyOf': [{'type': 'integer',
                                                                               'minimum': 12,
                                                                               'maximum': 70},
                                                                              {'type': 'null'}],
                                                                    'description': '妈妈当前周岁；传 null 表示清空。'},
                                                            'estimated_due_date': {'anyOf': [{'type': 'string',
                                                                                              'format': 'date'},
                                                                                             {'type': 'null'}],
                                                                                   'description': '预产期，格式 '
                                                                                                  'YYYY-MM-DD；仅用于尚无实际分娩日期的孕期资料。已有妈妈实际分娩日期或宝宝实际出生日期时，读取结果固定返回 '
                                                                                                  'null；传 null '
                                                                                                  '可清空数据库原始值。'},
                                                            'delivery_count': {'anyOf': [{'type': 'integer',
                                                                                          'minimum': 1,
                                                                                          'maximum': 20},
                                                                                         {'type': 'null'}],
                                                                               'description': '截至当前这次分娩的累计分娩次数；传 '
                                                                                              'null 表示清空。'},
                                                            'current_delivery_method': {'anyOf': [{'type': 'string',
                                                                                                   'enum': ['vaginal',
                                                                                                            'cesarean',
                                                                                                            'assisted_vaginal',
                                                                                                            'other',
                                                                                                            'unknown']},
                                                                                                  {'type': 'null'}],
                                                                                        'description': '当前这次分娩方式；传 '
                                                                                                       'null '
                                                                                                       '表示清空。'},
                                                            'actual_delivery_date': {'anyOf': [{'type': 'string',
                                                                                                'format': 'date'},
                                                                                               {'type': 'null'}],
                                                                                     'description': '当前这次实际分娩日期，格式 '
                                                                                                    'YYYY-MM-DD；设置后 '
                                                                                                    'profile_read '
                                                                                                    '不再暴露 '
                                                                                                    'estimated_due_date。'},
                                                            'has_cesarean_history': {'anyOf': [{'type': 'boolean'},
                                                                                               {'type': 'null'}],
                                                                                     'description': '当前或以前是否有过剖宫产；传 '
                                                                                                    'null '
                                                                                                    '表示尚未确认。'},
                                                            'current_feeding_mode': {'anyOf': [{'type': 'string',
                                                                                                'enum': ['exclusive_breastfeeding',
                                                                                                         'expressed_milk_feeding',
                                                                                                         'mixed_feeding',
                                                                                                         'formula_feeding',
                                                                                                         'unknown']},
                                                                                               {'type': 'null'}],
                                                                                     'description': '妈妈当前喂养模式；传 '
                                                                                                    'null '
                                                                                                    '表示清空。'}}},
                                  'infants': {'type': 'array',
                                              'minItems': 1,
                                              'maxItems': 10,
                                              'items': {'type': 'object',
                                                        'additionalProperties': False,
                                                        'minProperties': 2,
                                                        'required': ['infant_id'],
                                                        'properties': {'infant_id': {'type': 'string',
                                                                                     'format': 'uuid',
                                                                                     'description': 'profile_read '
                                                                                                    '返回的宝宝稳定 '
                                                                                                    'UUID。'},
                                                                       'name': {'type': 'string',
                                                                                'minLength': 1,
                                                                                'maxLength': 120,
                                                                                'description': '宝宝姓名或称呼。'},
                                                                       'sex_at_birth': {'anyOf': [{'type': 'string',
                                                                                                   'enum': ['female',
                                                                                                            'male',
                                                                                                            'intersex',
                                                                                                            'unknown',
                                                                                                            'undisclosed']},
                                                                                                  {'type': 'null'}],
                                                                                        'description': '宝宝出生时登记的生理性别；传 '
                                                                                                       'null '
                                                                                                       '表示清空。'},
                                                                       'birth_date': {'anyOf': [{'type': 'string',
                                                                                                 'format': 'date'},
                                                                                                {'type': 'null'}],
                                                                                      'description': '宝宝实际出生日期，格式 '
                                                                                                     'YYYY-MM-DD；传 '
                                                                                                     'null '
                                                                                                     '表示清空。'},
                                                                       'birth_weight_kg': {'anyOf': [{'type': 'number',
                                                                                                      'minimum': 0.2,
                                                                                                      'maximum': 10},
                                                                                                     {'type': 'null'}],
                                                                                           'description': '宝宝出生体重，单位 '
                                                                                                          'kg；传 '
                                                                                                          'null '
                                                                                                          '表示清空。'},
                                                                       'gestational_age_at_birth_days': {'anyOf': [{'type': 'integer',
                                                                                                                    'minimum': 140,
                                                                                                                    'maximum': 315},
                                                                                                                   {'type': 'null'}],
                                                                                                         'description': '宝宝出生孕周的标准总孕天数；传 '
                                                                                                                        'null '
                                                                                                                        '表示清空。'}}}},
                                  'current_infants': {'type': 'array',
                                                      'maxItems': 10,
                                                      'description': '完整替换当前这次分娩的宝宝关联；空数组表示清空关联。多宝宝必须分别给出连续且不重复的 '
                                                                     'birth_order。',
                                                      'items': {'type': 'object',
                                                                'additionalProperties': False,
                                                                'required': ['infant_id', 'birth_order'],
                                                                'properties': {'infant_id': {'type': 'string',
                                                                                             'format': 'uuid',
                                                                                             'description': 'profile_read '
                                                                                                            '返回的宝宝稳定 '
                                                                                                            'UUID。'},
                                                                               'birth_order': {'type': 'integer',
                                                                                               'minimum': 1,
                                                                                               'maximum': 10,
                                                                                               'description': '宝宝在当前这次分娩中的出生顺序，从 '
                                                                                                              '1 '
                                                                                                              '开始且必须连续。'}}}},
                                  'idempotency_key': {'type': 'string',
                                                      'minLength': 1,
                                                      'maxLength': 160,
                                                      'description': '可选幂等键；同一更新重试时复用相同值。'}},
                   'required': ['operation']},
 'schedule_timeline_read': {'type': 'object',
                            'additionalProperties': False,
                            'properties': {'start_date': {'type': 'string',
                                                          'format': 'date',
                                                          'description': '时间线起始本地日期，格式 '
                                                                         'YYYY-MM-DD，包含该日；省略时读取本地今天之前 7 天。'},
                                           'end_date': {'type': 'string',
                                                        'format': 'date',
                                                        'description': '时间线结束本地日期，格式 '
                                                                       'YYYY-MM-DD，包含该日；省略时读取本地今天之后 7 天。'},
                                           'domains': {'type': 'array',
                                                       'minItems': 1,
                                                       'maxItems': 4,
                                                       'uniqueItems': True,
                                                       'items': {'type': 'string',
                                                                 'enum': ['lactation',
                                                                          'pregnancy',
                                                                          'postpartum_recovery',
                                                                          'general']},
                                                       'description': '要读取的日程领域；省略时读取全部领域。'},
                                           'states': {'type': 'array',
                                                      'minItems': 1,
                                                      'maxItems': 4,
                                                      'uniqueItems': True,
                                                      'items': {'type': 'string',
                                                                'enum': ['pending',
                                                                         'completed',
                                                                         'skipped',
                                                                         'recorded']},
                                                      'description': '按归一化状态筛选；省略时返回全部状态。'},
                                           'limit': {'type': 'integer',
                                                     'minimum': 1,
                                                     'maximum': 50,
                                                     'default': 50,
                                                     'description': '最多返回的时间线项目数；关联日程和实际记录合并后只计为一个项目。'}}},
 'schedule_timeline_mutate': {'type': 'object',
                             'additionalProperties': False,
                             'required': ['operation', 'entry_type'],
                              'properties': {'operation': {'type': 'string',
                                                           'enum': ['create',
                                                                    'update',
                                                                    'delete',
                                                                    'set_status',
                                                                    'reschedule'],
                                                           'description': '执行一个时间线变更：create 新增，update '
                                                                          '更正，delete 删除，set_status '
                                                                          '修改完成状态，reschedule 调整单项或批量避让日程。'},
                                             'entry_type': {'type': 'string',
                                                            'enum': ['schedule', 'execution'],
                                                            'description': '变更对象类型：schedule 表示计划日程；execution '
                                                                           '表示实际喂养、吸奶或宝宝生长记录。'},
                                             'domain': {'type': 'string',
                                                        'enum': ['lactation',
                                                                 'pregnancy',
                                                                 'postpartum_recovery',
                                                                 'general'],
                                                        'description': 'create 时必填的日程领域；其他操作由后端根据现有任务确认。'},
                                             'task_id': {'type': 'string',
                                                         'format': 'uuid',
                                                         'description': '更新、删除、状态变更或单项改期的任务 '
                                                                        'UUID，必须来自 schedule_timeline_read。'},
                                             'plan_id': {'type': 'string',
                                                         'format': 'uuid',
                                                         'description': '新增日程可选的所属计划 UUID；批量重排时必填。'},
                                             'event_type': {'type': 'string',
                                                            'minLength': 1,
                                                            'maxLength': 64,
                                                            'description': '领域内事件类型，例如 feeding、appointment 或 exercise。'},
                                             'task_date': {'type': 'string',
                                                           'format': 'date',
                                                           'description': '计划日程的本地日期，格式 YYYY-MM-DD。'},
                                             'task_time': {'type': 'string',
                                                           'pattern': '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
                                                           'description': '可选的计划执行时间，使用本地 24 小时格式 HH:MM；全天任务省略。'},
                                             'title': {'type': 'string',
                                                       'minLength': 1,
                                                       'maxLength': 255,
                                                       'description': '日程任务或实际记录的简短标题。'},
                                             'description': {'type': 'string',
                                                             'maxLength': 2000,
                                                             'description': '计划日程说明；没有说明时省略。'},
                                             'completed': {'type': 'boolean',
                                                           'description': 'set_status 时为 true 表示完成，为 false '
                                                                          '表示恢复为待执行。完成 feeding/pumping '
                                                                          '泌乳任务时必须同时提交 occurred_at 和对应奶量。'},
                                             'record_type': {'type': 'string',
                                                             'enum': ['feeding', 'pumping', 'growth'],
                                                             'description': 'entry_type=execution 时的实际记录类型；完成泌乳任务时由后端根据任务确定。'},
                                             'record_id': {'type': 'string',
                                                           'format': 'uuid',
                                                           'description': '更新或删除实际记录时必填的记录 UUID，必须来自 '
                                                                          'schedule_timeline_read。'},
                                             'plan_task_id': {'type': 'string',
                                                              'format': 'uuid',
                                                              'description': '独立创建实际记录时可关联的日程任务 UUID；完成任务时由后端使用 task_id。'},
                                             'infant_id': {'type': 'string',
                                                           'format': 'uuid',
                                                           'description': '喂养或生长记录对应的宝宝 UUID。'},
                                             'occurred_at': {'type': 'string',
                                                             'format': 'date-time',
                                                             'description': '实际发生或测量时间，必须包含明确时区偏移。'},
                                             'ended_at': {'type': 'string',
                                                          'format': 'date-time',
                                                          'description': '吸奶结束时间；其他记录类型省略。'},
                                             'feed_type': {'type': 'string',
                                                           'minLength': 1,
                                                           'maxLength': 32,
                                                           'description': '喂养方式，例如 bottle 或 breastfeeding。'},
                                             'feed_action': {'type': 'string',
                                                             'maxLength': 32,
                                                             'description': '喂养动作或侧别。'},
                                             'volume_ml': {'type': 'number',
                                                           'minimum': 0,
                                                           'description': '宝宝侧本次实际摄入量，单位 ml；完成 feeding 任务时必填。'},
                                             'milk_volume_ml': {'type': 'number',
                                                                'minimum': 0,
                                                                'description': '妈妈侧本次实际吸奶产出量，单位 ml；完成 pumping 任务时必填。'},
                                             'duration_seconds': {'type': 'integer',
                                                                  'minimum': 0,
                                                                  'description': '本次喂养或吸奶持续时间，单位秒。'},
                                             'pump_type': {'type': 'string',
                                                           'maxLength': 32,
                                                           'description': '吸奶方式或设备类型。'},
                                             'source': {'type': 'string',
                                                        'maxLength': 32,
                                                        'description': '吸奶记录来源，例如 manual、agent 或 device。'},
                                             'height_cm': {'type': 'number',
                                                           'minimum': 0,
                                                           'description': '宝宝身高，单位 cm。'},
                                             'weight_kg': {'type': 'number',
                                                           'minimum': 0,
                                                           'description': '宝宝体重，单位 kg。'},
                                             'head_cm': {'type': 'number',
                                                         'minimum': 0,
                                                         'description': '宝宝头围，单位 cm。'},
                                             'reason': {'type': 'string',
                                                        'maxLength': 500,
                                                        'description': '删除日程、删除实际记录或调整日程的原因；用户没有说明时省略。'},
                                             'target_date': {'type': 'string',
                                                             'format': 'date',
                                                             'description': '批量重排的单个目标本地日期；与 target_dates '
                                                                            '二选一。'},
                                             'target_dates': {'type': 'array',
                                                              'minItems': 1,
                                                              'maxItems': 7,
                                                              'uniqueItems': True,
                                                              'items': {'type': 'string', 'format': 'date'},
                                                              'description': '批量重排的目标本地日期列表，最多 7 天。'},
                                             'busy_windows': {'type': 'array',
                                                              'minItems': 1,
                                                              'maxItems': 21,
                                                              'description': '已存在且仅用于避让的不可用时段，不会被重复创建。',
                                                              'items': {'type': 'object',
                                                                        'additionalProperties': False,
                                                                        'required': ['start_time', 'end_time'],
                                                                        'properties': {'date': {'type': 'string',
                                                                                                'format': 'date',
                                                                                                'description': '不可用时段的本地日期；省略时使用当前目标日期。'},
                                                                                       'start_time': {'type': 'string',
                                                                                                      'pattern': '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
                                                                                                      'description': '不可用时段开始时间，格式 '
                                                                                                                     'HH:MM。'},
                                                                                       'end_time': {'type': 'string',
                                                                                                    'pattern': '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
                                                                                                    'description': '不可用时段结束时间，格式 '
                                                                                                                   'HH:MM。'},
                                                                                       'title': {'type': 'string',
                                                                                                 'maxLength': 120,
                                                                                                 'description': '不可用时段标题；没有时省略。'}}}},
                                             'calendar_events': {'type': 'array',
                                                                 'minItems': 1,
                                                                 'maxItems': 21,
                                                                 'description': '用户本轮明确要求新增到日程、并参与奶量任务避让的生活事项。',
                                                                 'items': {'type': 'object',
                                                                           'additionalProperties': False,
                                                                           'required': ['date',
                                                                                        'start_time',
                                                                                        'end_time',
                                                                                        'title'],
                                                                           'properties': {'date': {'type': 'string',
                                                                                                   'format': 'date',
                                                                                                   'description': '生活事项的本地日期。'},
                                                                                          'start_time': {'type': 'string',
                                                                                                         'pattern': '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
                                                                                                         'description': '生活事项开始时间，格式 '
                                                                                                                        'HH:MM。'},
                                                                                          'end_time': {'type': 'string',
                                                                                                       'pattern': '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
                                                                                                       'description': '生活事项结束时间，格式 '
                                                                                                                      'HH:MM。'},
                                                                                          'title': {'type': 'string',
                                                                                                    'minLength': 1,
                                                                                                    'maxLength': 120,
                                                                                                    'description': '生活事项标题。'},
                                                                                          'description': {'type': 'string',
                                                                                                          'maxLength': 500,
                                                                                                          'description': '生活事项补充说明；没有时省略。'}}}},
                                             'min_gap_minutes': {'type': 'integer',
                                                                 'minimum': 0,
                                                                 'maximum': 360,
                                                                 'default': 90,
                                                                 'description': '批量重排时奶量任务与不可用时段之间的最小间隔分钟数。'},
                                             'default_duration_minutes': {'type': 'integer',
                                                                          'minimum': 1,
                                                                          'maximum': 240,
                                                                          'default': 30,
                                                                          'description': '批量重排时缺少明确时长的奶量任务默认持续分钟数。'},
                                             'idempotency_key': {'type': 'string',
                                                                 'minLength': 1,
                                                                 'maxLength': 255,
                                                                 'description': '可选幂等键；同一变更重试时复用相同值。'}}},
 'milk_analysis_manage': {'type': 'object',
                          'additionalProperties': False,
                          'required': ['operation'],
                          'properties': {'operation': {'type': 'string',
                                                       'enum': ['review',
                                                                'start_or_resume',
                                                                'answer',
                                                                'evaluate'],
                                                       'description': '奶量分析操作：review 读取确定性快照；start_or_resume '
                                                                      '开始或恢复六项采集；answer 提交本轮用户回答；evaluate 在 '
                                                                      'can_evaluate=true 后生成分析卡和计划准入结论。'},
                                         'detail_level': {'type': 'string',
                                                          'enum': ['summary', 'detailed'],
                                                          'default': 'summary',
                                                          'description': 'operation=review '
                                                                         '时选择状态摘要或包含实际记录、生长记录和趋势的详细分析快照。'},
                                         'days': {'type': 'integer',
                                                  'minimum': 1,
                                                  'maximum': 30,
                                                  'default': 7,
                                                  'description': 'operation=review 时快照覆盖的近期自然日数。'},
                                         'limit': {'type': 'integer',
                                                   'minimum': 1,
                                                   'maximum': 20,
                                                   'description': 'operation=review 时每类近期明细最多返回的记录数；省略时摘要模式使用 '
                                                                  '5，详细模式使用 8。'},
                                         'restart': {'type': 'boolean',
                                                     'default': False,
                                                     'description': '仅用于 operation=start_or_resume；为 true '
                                                                    '时明确放弃当前采集并重新开始，否则恢复进行中的采集，或在没有进行中采集时开始。'},
                                         'observed_answers': {'type': 'array',
                                                              'maxItems': 5,
                                                              'description': '仅用于 '
                                                                             'operation=answer；列出本轮用户原话中明确回答到的一个或多个采集字段，evidence '
                                                                             '必须逐字来自本轮消息。',
                                                              'items': {'type': 'object',
                                                                        'additionalProperties': False,
                                                                        'required': ['field', 'evidence'],
                                                                        'properties': {'field': {'type': 'string',
                                                                                                 'enum': ['infant_wet_diapers',
                                                                                                          'infant_state_or_satisfaction',
                                                                                                          'infant_growth_signal',
                                                                                                          'maternal_red_flags',
                                                                                                          'maternal_breast_comfort'],
                                                                                                 'description': '本轮用户原话明确覆盖的奶量分析采集字段。'},
                                                                                       'evidence': {'type': 'string',
                                                                                                    'minLength': 1,
                                                                                                    'maxLength': 500,
                                                                                                    'description': '能够支持该字段的本轮用户原话片段，不改写、不推断。'}}}}}},
 'diary_read': {'type': 'object',
                          'additionalProperties': False,
                          'properties': {'entry_date': {'type': 'string',
                                                        'minLength': 1,
                                                        'maxLength': 20,
                                                        'description': '读取单日日记的 YYYY-MM-DD 日期；省略时按日期范围列出日记。'},
                                         'start_date': {'type': 'string',
                                                        'maxLength': 20,
                                                        'description': '日期范围起点，格式为 YYYY-MM-DD。'},
                                         'end_date': {'type': 'string',
                                                      'maxLength': 20,
                                                      'description': '日期范围终点，格式为 YYYY-MM-DD。'},
                                         'limit': {'type': 'integer',
                                                   'minimum': 1,
                                                   'maximum': 30,
                                                   'default': 7,
                                                   'description': '最多返回的日记条数。'}}},
 'diary_mutate': {'type': 'object',
                           'additionalProperties': False,
                           'required': ['operation'],
                           'properties': {'operation': {'type': 'string',
                                                        'enum': ['create', 'update', 'delete'],
                                                        'description': '创建新日记、完整重写已有日记或删除已有日记。'},
                                          'entry_date': {'type': 'string',
                                                         'minLength': 1,
                                                         'maxLength': 20,
                                                         'description': 'YYYY-MM-DD 日期；create/update '
                                                                        '省略时使用当前用户本地日期，delete 必须提供。'},
                                          'content': {'type': 'string',
                                                      'minLength': 1,
                                                      'maxLength': 5000,
                                                      'description': 'create/update 必填的完整正文；update '
                                                                     '必须包含旧正文和本轮新增事实的完整重写结果。'},
                                          'confirmation_evidence': {'type': 'string',
                                                                    'minLength': 1,
                                                                    'maxLength': 500,
                                                                    'description': 'delete '
                                                                                   '必填，逐字引用当前用户消息中表达删除确认的短原文。'}}},
 'devices_guidance_manage': {'type': 'object',
                             'additionalProperties': False,
                             'required': ['model', 'operation'],
                             'properties': {'model': {'type': 'string',
                                                      'minLength': 1,
                                                      'maxLength': 120,
                                                      'description': '已经由用户确认的设备型号；当前支持 Air1 或 BP334。'},
                                            'operation': {'type': 'string',
                                                          'enum': ['read',
                                                                   'start_or_resume',
                                                                   'complete_current',
                                                                   'cancel'],
                                                          'description': '读取目标内容、开始或恢复开箱指导、完成当前步骤并推进一步，或取消开箱指导。'},
                                            'topic': {'type': 'string',
                                                      'enum': ['unboxing',
                                                               'setup',
                                                               'assembly',
                                                               'cleaning',
                                                               'disinfection',
                                                               'charging',
                                                               'bluetooth',
                                                               'flange'],
                                                      'maxLength': 80,
                                                      'description': '可选说明书主题，例如 setup、cleaning、flange 或 '
                                                                     'bluetooth。'},
                                            'step': {'type': 'string',
                                                     'maxLength': 80,
                                                     'description': '需要读取的明确指导步骤，例如 guide.parts、guide.charging '
                                                                    '或 guide.assembly。'},
                                            'resource_kind': {'type': 'string',
                                                              'enum': ['auto', 'image', 'pdf', 'video'],
                                                              'default': 'auto',
                                                              'description': '可选素材类型；默认由服务自动选择。'},
                                            'measured_nipple_mm': {'type': 'number',
                                                                   'minimum': 0,
                                                                   'description': '用户提供的乳头根部测量值，供回复时按官方素材核对。'}}},
 'pump_models_read': {'type': 'object', 'additionalProperties': False, 'properties': {}},
 'conversation_history_image_read': {'type': 'object',
                                     'additionalProperties': False,
                                     'required': ['image_url'],
                                     'properties': {'image_url': {'type': 'string',
                                                                  'minLength': 1,
                                                                  'maxLength': 2048,
                                                                  'description': '当前可见对话历史中由智能体此前回复展示过的目标图片 '
                                                                                 'URL。'},
                                                    'detail': {'type': 'string',
                                                               'enum': ['low', 'high'],
                                                               'default': 'low',
                                                               'description': '普通内容识别使用 low；小字或精细结构识别使用 '
                                                                              'high。'}}},
 'plan_read': {'type': 'object',
               'additionalProperties': False,
               'required': ['mode'],
               'properties': {'mode': {'type': 'string',
                                       'enum': ['list', 'detail'],
                                       'description': 'list 返回计划列表；detail 返回一个精确计划。'},
                              'plan_id': {'type': 'string',
                                          'format': 'uuid',
                                          'description': 'detail 模式必填的计划 UUID，必须来自可信读取结果。'},
                              'plan_type': {'type': 'string',
                                            'minLength': 1,
                                            'maxLength': 64,
                                            'description': 'list 模式可选的计划类型精确过滤条件。'},
                              'status': {'type': 'string',
                                         'minLength': 1,
                                         'maxLength': 32,
                                         'default': 'active',
                                         'description': 'list 模式的计划状态过滤条件，默认 active。'},
                              'include_content': {'type': 'boolean',
                                                  'default': False,
                                                  'description': '是否返回按计划类型裁剪后的安全计划内容；仅需摘要时保持 false。'},
                              'limit': {'type': 'integer',
                                        'minimum': 1,
                                        'maximum': 50,
                                        'default': 20,
                                        'description': 'list 模式最多返回的计划数量。'}}},
 'plan_mutate': {'type': 'object',
                 'additionalProperties': False,
                 'required': ['operation'],
                 'properties': {'operation': {'type': 'string',
                                              'enum': ['create', 'update', 'delete'],
                                              'description': '计划资源操作：创建、更新计划元数据或删除整个计划。'},
                                'plan_type': {'type': 'string',
                                              'minLength': 1,
                                              'maxLength': 64,
                                              'examples': ['milk_management', 'pregnancy'],
                                              'description': 'create 时必填；当前可创建 milk_management 或 pregnancy。update/delete '
                                                             '时可省略，真实类型由后端读取；传入时仅作一致性提示。'},
                                'plan_id': {'type': 'string',
                                            'format': 'uuid',
                                            'description': 'update/delete 时必填的计划 UUID，必须来自 plan_read 或其他可信 owner-scoped 结果。'},
                                'expected_version': {'type': 'integer',
                                                     'minimum': 1,
                                                     'description': 'update 时必填的计划版本，必须来自最近一次 plan_read。'},
                                'title': {'type': 'string',
                                          'minLength': 1,
                                          'maxLength': 255,
                                          'description': 'update 时可修改的计划标题；创建领域计划时由后端生成。'},
                                'summary': {'type': 'string',
                                            'maxLength': 2000,
                                            'description': 'update 时可修改的计划摘要；创建孕期计划时仅使用用户明确确认的摘要。'},
                                'direction': {'type': 'string',
                                              'enum': ['increase', 'maintain', 'decrease'],
                                              'description': '创建 milk_management 计划时必填的追奶、稳奶或减奶方向。'},
                                'start_date': {'type': 'string',
                                               'format': 'date',
                                               'description': '创建奶量计划时可选的开始日期；省略时由 runtime 决定。'},
                                'days': {'type': 'integer',
                                         'minimum': 1,
                                         'maximum': 30,
                                         'default': 7,
                                         'description': '创建奶量计划时可选的覆盖天数。'},
                                'target_daily_ml': {'type': 'number',
                                                    'minimum': 0,
                                                    'maximum': 5000,
                                                    'description': '仅当用户明确给出阶段日目标时用于创建奶量计划。'},
                                'preferred_pumping_times': {'type': 'array',
                                                            'minItems': 1,
                                                            'maxItems': 10,
                                                            'uniqueItems': True,
                                                            'items': {'type': 'string',
                                                                      'pattern': '^(?:[01]?\\d|2[0-3]):[0-5]\\d$'},
                                                            'description': '创建奶量计划时，仅传用户明确指定的可执行吸奶时间。'},
                                'calendar_write_strategy': {'type': 'string',
                                                            'enum': ['append',
                                                                     'replace_future_plan_tasks'],
                                                            'description': '已有未来奶量任务且用户明确选择后使用的日程写入策略。'},
                                'scope': {'type': 'string',
                                          'enum': ['full', 'prenatal_only', 'short_range'],
                                          'description': '创建 pregnancy 计划时可选的已确认计划范围。'},
                                'reason': {'type': 'string',
                                           'maxLength': 500,
                                           'description': '删除整个计划时可选的用户原因。'},
                                'idempotency_key': {'type': 'string',
                                                    'minLength': 1,
                                                    'maxLength': 255,
                                                    'description': '可选幂等键；同一计划变更重试时复用相同值。'}}},
 'pregnancy_intake_manage': {'type': 'object',
                           'additionalProperties': False,
                           'required': ['command'],
                           'properties': {'command': {'type': 'string',
                                                      'enum': ['start_or_resume',
                                                               'submit_form',
                                                               'answer_current',
                                                               'edit_answer',
                                                               'pause',
                                                               'resume',
                                                               'abandon'],
                                                      'description': '本次只执行一个状态机命令；不要自行推测或传入内部阶段。'},
                                          'choice_id': {'type': 'string',
                                                        'maxLength': 120,
                                                        'description': '当前步骤展示的稳定选项 id；自由文本回答时可省略。'},
                                          'answer': {'type': 'string',
                                                     'maxLength': 2000,
                                                     'description': '用户本轮明确提供的自由文本答案；不得填入模型推断。'},
                                          'step_id': {'type': 'string',
                                                      'maxLength': 120,
                                                      'description': '仅 edit_answer 使用，必须来自工具返回的可编辑步骤 id。'},
                                          'restart': {'type': 'boolean',
                                                      'description': '仅当用户明确要求放弃当前采集并重新开始时为 true。'}}},
 'hospital_bag_cart_mutate': {'type': 'object',
                             'additionalProperties': False,
                             'required': ['operation'],
                             'properties': {'operation': {'type': 'string',
                                                          'enum': ['replace_pump_model',
                                                                   'add_pump_model',
                                                                   'optimize_budget',
                                                                   'remove_items',
                                                                   'restore_items',
                                                                   'replace_items',
                                                                   'mark_provided',
                                                                   'mark_owned',
                                                                   'update_quantity',
                                                                   'reset_cart',
                                                                   'clarify']},
                                            'item_ids': {'type': 'array',
                                                         'maxItems': 40,
                                                         'items': {'type': 'string', 'maxLength': 120}},
                                            'product_sku_id': {'type': ['string', 'null'], 'maxLength': 120},
                                            'quantity_updates': {'type': 'array',
                                                                 'maxItems': 40,
                                                                 'items': {'type': 'object',
                                                                           'additionalProperties': False,
                                                                           'required': ['item_id', 'qty'],
                                                                           'properties': {'item_id': {'type': 'string',
                                                                                                      'maxLength': 120},
                                                                                          'qty': {'type': 'integer',
                                                                                                  'minimum': 0,
                                                                                                  'maximum': 99}}}},
                                            'target_budget': {'type': ['number', 'null'], 'minimum': 0},
                                            'budget_mode': {'type': 'string',
                                                            'enum': ['under',
                                                                     'around',
                                                                     'cheaper',
                                                                     'minimal',
                                                                     'none']},
                                            'preference': {'type': 'string',
                                                           'enum': ['balanced',
                                                                    'cheapest',
                                                                    'comfort',
                                                                    'breastfeeding',
                                                                    'minimal',
                                                                    'budget',
                                                                    'portable',
                                                                    'performance',
                                                                    'app',
                                                                    'simple',
                                                                    'premium']},
                                            'preserve_item_ids': {'type': 'array',
                                                                  'maxItems': 40,
                                                                  'items': {'type': 'string',
                                                                            'maxLength': 120}},
                                            'allow_remove_pump': {'type': 'boolean'},
                                            'idempotency_key': {'type': 'string', 'maxLength': 255}}},
 'ibclc_consult_card_create': {'type': 'object',
                              'additionalProperties': False,
                              'required': ['operation', 'reason'],
                              'properties': {'operation': {'type': 'string', 'enum': ['create']},
                                             'reason': {'type': 'string', 'minLength': 1, 'maxLength': 500},
                                             'feeding_context': {'type': 'string', 'maxLength': 2000},
                                             'urgency': {'type': 'string',
                                                         'enum': ['routine', 'soon', 'urgent']},
                                             'preferred_language': {'type': 'string', 'maxLength': 80},
                                             'payload': {'type': 'object', 'additionalProperties': True},
                                             'locale': {'type': 'string', 'maxLength': 35},
                                             'timezone': {'type': 'string', 'maxLength': 80}}},
 'support_ticket_create': {'type': 'object',
                          'additionalProperties': False,
                          'required': ['operation', 'issue_summary', 'user_confirmed'],
                          'properties': {'operation': {'type': 'string', 'enum': ['create']},
                                         'issue_type': {'type': 'string',
                                                        'enum': ['malfunction',
                                                                 'missing_parts',
                                                                 'defect',
                                                                 'warranty',
                                                                 'return_or_refund',
                                                                 'order_or_shipping',
                                                                 'usage_help',
                                                                 'safety_concern',
                                                                 'other']},
                                         'issue_summary': {'type': 'string',
                                                           'description': '面向客服和用户的简洁问题摘要，用于预填工单。',
                                                           'minLength': 1,
                                                           'maxLength': 2000},
                                         'product_model': {'type': 'string', 'maxLength': 120},
                                         'order_number': {'type': 'string', 'maxLength': 120},
                                         'purchase_channel': {'type': 'string', 'maxLength': 120},
                                         'user_contact': {'type': 'string', 'maxLength': 255},
                                         'troubleshooting_done': {'type': 'array',
                                                                  'items': {'type': 'string', 'maxLength': 500},
                                                                  'maxItems': 20},
                                         'urgency': {'type': 'string', 'enum': ['normal', 'high', 'safety']},
                                         'user_emotion': {'type': 'string', 'maxLength': 500},
                                         'attachments_note': {'type': 'string', 'maxLength': 1000},
                                         'user_confirmed': {'type': 'boolean',
                                                            'description': '只有用户明确同意现在创建售后工单时才传 true。'},
                                         'locale': {'type': 'string', 'maxLength': 35}}},
 'hospital_bag_manage': {'type': 'object',
                         'additionalProperties': False,
                         'properties': {'generation_mode': {'type': 'string',
                                                            'enum': ['standard', 'quick', 'immediate']},
                                        'restart': {'type': 'boolean',
                                                    'description': '仅当用户明确要求重新采集待产包信息时传 true。'}}}}



def input_schema_for_tool(tool_name: str) -> JsonSchema:
    schema = _TOOL_INPUT_SCHEMAS.get(tool_name)
    if schema is None:
        raise ApiError(code="tool_schema_not_found", message="Tool input schema is not registered.", status=500)
    return deepcopy(schema)


def input_schema_tool_names() -> tuple[str, ...]:
    return tuple(sorted(_TOOL_INPUT_SCHEMAS))
