from __future__ import annotations

from typing import Any

from production_backend.app.core.errors import ApiError

from .contracts import ToolContract
from .schemas import input_schema_for_tool


class ToolContractRegistry:
    def __init__(self) -> None:
        self._contracts: dict[str, ToolContract] = {}

    def register(self, contract: ToolContract) -> None:
        if contract.name in self._contracts:
            raise ApiError(code="conflict", message="Tool contract is already registered.", status=409)
        self._contracts[contract.name] = contract

    def get(self, name: str) -> ToolContract:
        contract = self._contracts.get(name)
        if contract is None:
            raise ApiError(code="not_found", message="Tool contract not found.", status=404)
        return contract

    def list(self) -> list[ToolContract]:
        return list(self._contracts.values())

    def names_for_sdk(self) -> tuple[str, ...]:
        return tuple(sorted(self._contracts))

    def eager_names(self) -> tuple[str, ...]:
        return tuple(sorted(contract.name for contract in self._contracts.values() if contract.loading_mode == "eager"))

    def deferred_names(self) -> tuple[str, ...]:
        return tuple(sorted(contract.name for contract in self._contracts.values() if contract.loading_mode == "deferred"))


def _tool_contract(*, name: str, **values: Any) -> ToolContract:
    return ToolContract(name=name, input_schema=input_schema_for_tool(name), **values)


def default_tool_registry() -> ToolContractRegistry:
    registry = ToolContractRegistry()
    registry.register(
        _tool_contract(
            name="load_service_skill",
            domain="agent_runtime",
            description=(
                "按 service_skill_id 加载一个 MomCozy 服务技能。"
                "用户当前请求需要进入奶量、产前准备、健康咨询、情绪支持或设备指导流程，且对应技能尚未驻留时调用；"
                "返回该技能说明、建议工具和小型业务事实包。"
            ),
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=20,
        )
    )
    registry.register(
        _tool_contract(
            name="profile.read",
            domain="profiles",
            description="读取当前用户及宝宝的基础资料投影。用户的问题或后续动作需要核对姓名、年龄、孕产状态或宝宝资料时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="profile_update",
            domain="global",
            description="更新当前用户的基础资料。用户明确提供或更正姓名、年龄或 onboarding 状态时调用。",
            loading_mode="eager",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="records.milk_summary.read",
            domain="records",
            description="读取当前用户近期喂养、吸奶和趋势记录的简要摘要。用户要回顾近期记录或需要奶量管理概览时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="records.milk_status.read",
            domain="records",
            description="读取当前用户近期奶量状态的确定性快照。用户询问当前奶量表现、近期是否有记录或今日状态时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="records.milk_analysis.read",
            domain="records",
            description="读取当前用户近期奶量、宝宝生长和趋势事实并生成分析快照。用户要分析奶量变化、趋势或与生长记录的关系时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="records.growth.read",
            domain="records",
            description="读取当前用户宝宝的身高、体重和头围等生长记录。用户要查看宝宝近期生长数据或趋势时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.current.read",
            domain="plans",
            description="读取当前用户生效中的计划和近期任务摘要。用户要查看当前计划、待办或后续安排时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.calendar.read",
            domain="plans",
            description="按日期和状态读取当前用户的计划任务日程。用户询问某天安排、待完成事项或任务状态时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy_diary.entries.read",
            domain="pregnancy_diary",
            description="读取当前用户某一天或一个日期范围内的孕期日记。用户要查看、回顾、整理历史日记，或需要核对某日原文时调用。",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy_diary.entry.create",
            domain="pregnancy_diary",
            description=(
                "同步创建当前用户指定日期的孕期日记并返回已写入记录。"
                "用户明确要求保存，或第一人称具体讲述可留存的孕期事实且没有拒绝记录时调用。"
                "目标日期已有记录时返回 entry_already_exists；此时必须继续调用更新工具 append 本轮事实，不能说已经保存。"
            ),
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy_diary.entry.update",
            domain="pregnancy_diary",
            description=(
                "同步补充或修改当前用户指定日期已有的孕期日记并返回更新后记录。"
                "用户明确要求追加、更正或重写已有记录，或创建发现同日记录后继续保存本轮事实时调用；正文可选择 append 或 replace。"
                "返回 entry_not_found 时没有发生写入，不能说已经更新。"
            ),
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy_diary.entry.delete.propose",
            domain="pregnancy_diary",
            description="为当前用户指定日期的孕期日记创建删除确认。用户明确要求删除且已确定目标日期时调用；用户确认后执行删除。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="devices.pump_status.read",
            domain="devices",
            description="读取当前用户吸奶器设备及近期遥测状态摘要。用户询问设备连接、在线状态、固件或近期运行状态时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="devices.guidance_assets.read",
            domain="devices",
            description="读取 Momcozy 设备的官方指导图片、视频和文档素材。用户需要安装、使用、清洁或排查设备问题的指导内容时调用。",
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="images.inspect",
            domain="images",
            description=(
                "查看当前可见对话历史中已经展示过的一张图片。"
                "用户询问上图、这张图或历史回复中某张具体图片的可见内容时调用，并传入对应 image_url。"
            ),
            loading_mode="eager",
            read_or_write="read",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.milk_plan.propose",
            domain="plans",
            description="创建当前用户的奶量计划预览并发起待确认动作。用户明确希望制定泌乳、喂养或吸奶计划时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="pregnancy.plan.propose",
            domain="plans",
            description="基于可信孕期资料和本轮偏好创建孕期计划预览并发起待确认动作。用户明确希望制定孕期计划时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.task_create.propose",
            domain="plans",
            description="为当前用户的计划创建一个待确认任务。用户明确要求新增某项待办、安排或计划任务时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.task_complete.propose",
            domain="plans",
            description="把当前用户指定的计划任务标记为完成并等待确认。用户明确表示某项任务已经完成时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.task_update.propose",
            domain="plans",
            description="修改当前用户指定计划任务的日期、时间、标题、描述或载荷并等待确认。用户明确要求调整已有任务时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.task_delete.propose",
            domain="plans",
            description="为当前用户指定的计划任务创建删除确认。用户明确要求删除已有任务时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="plans.plan_delete.propose",
            domain="plans",
            description="为当前用户指定的计划创建删除确认。用户明确要求删除整个已有计划时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="notifications.milk_reminder.propose",
            domain="notifications",
            description="为当前用户创建奶量、喂养或吸奶提醒并等待确认。用户明确要求在指定时间收到相关提醒时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.feeding_record.propose",
            domain="records",
            description="保存当前用户明确提供的一次喂养记录。用户要求记录喂养时间、方式或奶量时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.pumping_record.propose",
            domain="records",
            description="保存当前用户明确提供的一次吸奶记录。用户要求记录吸奶时间、时长、档位或奶量时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.feeding_record_delete.propose",
            domain="records",
            description="为当前用户指定的喂养记录创建删除确认。用户明确要求删除某次已有喂养记录时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.pumping_record_delete.propose",
            domain="records",
            description="为当前用户指定的吸奶记录创建删除确认。用户明确要求删除某次已有吸奶记录时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.growth_record.propose",
            domain="records",
            description="保存当前用户明确提供的一次宝宝生长记录。用户要求记录宝宝身高、体重或头围时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.growth_record_update.propose",
            domain="records",
            description="修改当前用户宝宝的指定生长记录并等待确认。用户明确要求更正已有身高、体重或头围记录时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="records.growth_record_delete.propose",
            domain="records",
            description="为当前用户宝宝的指定生长记录创建删除确认。用户明确要求删除已有生长记录时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="birth_plan_form_create",
            domain="birth_prep",
            description="创建分娩沟通单信息采集表单，字段和预填信息由 runtime 生成。用户希望开始梳理分娩偏好或准备分娩沟通单时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="labor_communication_card_create",
            domain="birth_prep",
            description="根据应用侧可信的 birth_plan_card_intake 表单提交生成可渲染的分娩沟通单。用户完成信息采集并要求生成沟通单时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_form_create",
            domain="hospital_bag",
            description="创建待产包信息采集表单，并由 runtime 合并可信资料和当前孕期计划。用户确认开始整理待产包时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_card_create",
            domain="hospital_bag",
            description="根据应用侧可信的 hospital_bag_intake 表单提交生成可渲染的待产包清单。用户完成信息采集并要求生成待产包清单时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_cart_update",
            domain="hospital_bag",
            description=(
                "修改当前用户已有的待产包购物车并返回前端可应用的更新。"
                "用户在待产包购物车场景中要求调整预算、增删商品、修改数量、标记已有物品、恢复默认或同步已推荐吸奶器时调用；"
                "用户给出明确预算金额时使用 optimize_budget 和 target_budget。"
            ),
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="hospital_bag_pump_recommend",
            domain="hospital_bag",
            description=(
                "根据当前用户的预算、使用场景和偏好，从 Momcozy 官方目录推荐吸奶器型号并返回购物车同步建议。"
                "用户在购买前询问适合的型号、型号差异、预算内选择、价格或点名某型号时调用。"
            ),
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="support.ticket.propose",
            domain="support",
            description="为当前用户创建 Momcozy 设备售后工单并等待确认。用户明确希望把设备故障或服务问题提交给售后处理时调用。",
            read_or_write="write",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        _tool_contract(
            name="ibclc_consult_card_create",
            domain="support",
            description="为当前用户创建 IBCLC 哺乳顾问咨询入口卡片。用户希望联系专业哺乳顾问或需要进一步人工咨询时调用。",
            read_or_write="write",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    return registry
