from __future__ import annotations

from ....core.errors import ApiError
from .contracts import ToolContract


class ToolContractRegistry:
    def __init__(self) -> None:
        self._contracts: dict[str, ToolContract] = {}

    def register(self, contract: ToolContract) -> None:
        if contract.name in self._contracts:
            raise ApiError(code="conflict", message="Tool contract is already registered.", status=409)
        self._contracts[contract.name] = contract

    def get(self, name: str) -> ToolContract:
        contract = self._contracts.get(name)
        if contract is None:
            raise ApiError(code="not_found", message="Tool contract not found.", status=404)
        return contract

    def list(self) -> list[ToolContract]:
        return list(self._contracts.values())

    def names_for_sdk(self) -> tuple[str, ...]:
        return tuple(sorted(self._contracts))


def default_tool_registry() -> ToolContractRegistry:
    registry = ToolContractRegistry()
    registry.register(
        ToolContract(
            name="profile.read",
            domain="profiles",
            description="读取当前用户的用户资料上下文投影。",
            input_schema_ref="ProfileContextQuery",
            output_schema_ref="ProfileContextRead",
            read_or_write="read",
            required_permission="profile:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="business.context.read",
            domain="business_context",
            description="读取当前用户近期记录、计划、日记和设备上下文的有限摘要。",
            input_schema_ref="BusinessContextQuery",
            output_schema_ref="BusinessContextRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="records.milk_summary.read",
            domain="records",
            description="从近期喂养、吸奶和趋势记录中读取有限奶量管理摘要。",
            input_schema_ref="MilkSummaryQuery",
            output_schema_ref="MilkSummaryRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="records.milk_status.read",
            domain="records",
            description="从近期喂养、吸奶和趋势记录中读取确定性奶量状态快照。",
            input_schema_ref="MilkStatusQuery",
            output_schema_ref="MilkStatusRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="plans.current.read",
            domain="plans",
            description="读取当前用户生效中计划和近期任务的有限摘要。",
            input_schema_ref="PlansCurrentQuery",
            output_schema_ref="PlansCurrentRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="diary.recent.read",
            domain="diary",
            description="读取当前用户近期孕期日记条目的有限摘要。",
            input_schema_ref="DiaryRecentQuery",
            output_schema_ref="DiaryRecentRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="diary.entry_upsert.propose",
            domain="diary",
            description="提出孕期日记写入或更新动作，等待用户确认。",
            input_schema_ref="DiaryEntryUpsertProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="diary:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="pregnancy.plan_context.read",
            domain="plans",
            description="读取当前孕期用户资料、生效中计划、任务和近期日记上下文的有限摘要。",
            input_schema_ref="PregnancyPlanContextQuery",
            output_schema_ref="PregnancyPlanContextRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="memory.create.propose",
            domain="memory",
            description="提出长期记忆写入动作，等待用户确认。",
            input_schema_ref="MemoryCreateProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="memory:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="devices.pump_status.read",
            domain="devices",
            description="读取当前用户吸奶器设备和近期遥测状态的有限摘要。",
            input_schema_ref="DevicesPumpStatusQuery",
            output_schema_ref="DevicesPumpStatusRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="devices.guidance_assets.read",
            domain="devices",
            description="按元数据读取已打包设备指导素材的有限列表。",
            input_schema_ref="DeviceGuidanceAssetsQuery",
            output_schema_ref="DeviceGuidanceAssetsRead",
            read_or_write="read",
            required_permission="business_context:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=10,
        )
    )
    registry.register(
        ToolContract(
            name="files.vision_summary.read",
            domain="files",
            description="读取当前用户拥有的上传图片，并返回有限视觉摘要。",
            input_schema_ref="FileVisionSummaryQuery",
            output_schema_ref="FileVisionSummaryRead",
            read_or_write="read",
            required_permission="files:read:self",
            owner_scope="actor",
            side_effect_level="none",
            blocking_policy="must_wait",
            result_dependency="next_tool_call",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=False,
            timeout_seconds=20,
        )
    )
    registry.register(
        ToolContract(
            name="plans.milk_plan.propose",
            domain="plans",
            description="提出奶量管理计划创建动作，等待用户确认。",
            input_schema_ref="MilkPlanProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="plans:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="pregnancy.plan_create.propose",
            domain="plans",
            description="提出孕期计划创建动作，等待用户确认。",
            input_schema_ref="PregnancyPlanProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="plans:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="plans.task_create.propose",
            domain="plans",
            description="提出计划任务创建动作，等待用户确认。",
            input_schema_ref="PlanTaskCreateProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="plans:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="plans.task_complete.propose",
            domain="plans",
            description="提出计划任务完成状态更新动作，等待用户确认。",
            input_schema_ref="PlanTaskCompleteProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="plans:write:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="notifications.milk_reminder.propose",
            domain="notifications",
            description="提出奶量管理提醒通知动作，等待用户确认。",
            input_schema_ref="MilkReminderProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="notifications:create:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="records.feeding_record.propose",
            domain="records",
            description="提出喂养记录创建动作。",
            input_schema_ref="FeedingRecordProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="records:write:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="records.pumping_record.propose",
            domain="records",
            description="提出吸奶记录创建动作。",
            input_schema_ref="PumpingRecordProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="records:write:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="hospital_bag.cart_update.propose",
            domain="hospital_bag",
            description="提出待产包购物车更新动作。",
            input_schema_ref="HospitalBagCartUpdateProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="hospital_bag_cart:update:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="enqueue_and_continue",
            result_dependency="none",
            requires_confirmation=False,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="artifacts.hospital_bag_card.create",
            domain="artifacts",
            description="为当前智能体运行创建当前用户范围内的待产包卡片产物。",
            input_schema_ref="AgentArtifactCreate",
            output_schema_ref="AgentArtifactRead",
            read_or_write="write",
            required_permission="agent_artifact:create:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="artifacts.labor_communication_card.create",
            domain="artifacts",
            description="为当前智能体运行创建当前用户范围内的分娩沟通单产物。",
            input_schema_ref="AgentArtifactCreate",
            output_schema_ref="AgentArtifactRead",
            read_or_write="write",
            required_permission="agent_artifact:create:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="artifacts.lactation_summary.create",
            domain="artifacts",
            description="为当前智能体运行创建当前用户范围内的泌乳分析摘要产物。",
            input_schema_ref="AgentArtifactCreate",
            output_schema_ref="AgentArtifactRead",
            read_or_write="write",
            required_permission="agent_artifact:create:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="artifacts.postpartum_checkin.create",
            domain="artifacts",
            description="为当前智能体运行创建当前用户范围内的产后恢复状态打卡产物。",
            input_schema_ref="AgentArtifactCreate",
            output_schema_ref="AgentArtifactRead",
            read_or_write="write",
            required_permission="agent_artifact:create:self",
            owner_scope="actor",
            side_effect_level="low",
            blocking_policy="must_wait",
            result_dependency="final_response",
            requires_confirmation=False,
            idempotency_required=False,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    registry.register(
        ToolContract(
            name="support.ticket.propose",
            domain="support",
            description="在用户确认意图明确后，创建售后工单动作提案。",
            input_schema_ref="SupportTicketProposalCreate",
            output_schema_ref="AgentActionRead",
            read_or_write="write",
            required_permission="support_ticket:create:self",
            owner_scope="actor",
            side_effect_level="medium",
            blocking_policy="wait_for_confirmation",
            result_dependency="none",
            requires_confirmation=True,
            idempotency_required=True,
            audit_required=True,
            timeout_seconds=15,
        )
    )
    return registry
